name: Terraform Format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.2
      - run: terraform fmt -check -recursive
